# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('vehicle_type', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='motors-photos/')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=150)),
                ('color', models.CharField(max_length=100)),
                ('no_of_seats', models.IntegerField()),
                ('engine', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='motors-photos/')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motors.Vehicle')),
            ],
        ),
    ]
