# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicledetails',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vehicledetails',
            name='vehicle',
        ),
        migrations.DeleteModel(
            name='VehicleDetails',
        ),
    ]
