# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0002_auto_20171214_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=150)),
                ('color', models.CharField(max_length=100)),
                ('no_of_seats', models.IntegerField()),
                ('engine', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='motors-photos/')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motors.Category')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motors.Vehicle')),
            ],
        ),
    ]
