# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 08:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0002_auto_20171213_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='description',
            field=models.TextField(default=datetime.datetime(2017, 12, 13, 8, 27, 26, 257115, tzinfo=utc), max_length=600),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='vehicledetails',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
