# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0003_auto_20171213_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='motors-photos/')),
                ('description', models.TextField(max_length=600)),
            ],
        ),
    ]
